-- CreateTable
CREATE TABLE `Property` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `title` VARCHAR(191) NOT NULL,
    `description` TEXT NULL,
    `fullDescription` TEXT NULL,
    `propertyType` VARCHAR(191) NOT NULL DEFAULT 'apartment',
    `transactionType` VARCHAR(191) NOT NULL DEFAULT 'sale',
    `price` DOUBLE NULL,
    `area` DOUBLE NULL,
    `bedrooms` INTEGER NOT NULL DEFAULT 0,
    `bathrooms` INTEGER NOT NULL DEFAULT 0,
    `parkingSpots` INTEGER NOT NULL DEFAULT 0,
    `block` VARCHAR(191) NULL,
    `building` VARCHAR(191) NULL,
    `apartmentNumber` VARCHAR(191) NULL,
    `address` VARCHAR(191) NULL,
    `neighborhood` VARCHAR(191) NULL,
    `city` VARCHAR(191) NULL,
    `state` VARCHAR(191) NULL,
    `zipCode` VARCHAR(191) NULL,
    `features` TEXT NULL,
    `imageUrl` VARCHAR(191) NULL,
    `galleryUrls` TEXT NULL,
    `isFeatured` BOOLEAN NOT NULL DEFAULT false,
    `isActive` BOOLEAN NOT NULL DEFAULT true,
    `ownerName` VARCHAR(191) NULL,
    `ownerWhatsapp` VARCHAR(191) NULL,
    `userId` INTEGER NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
